name: cat_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  built_value: ^8.1.3
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/wildcats.png
      - assets/images/badmoodcats.png

  fonts:
      - family: Lobster
        fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf
 
